name: Deploy Dev Environment

on:
  workflow_dispatch:

jobs:
  run-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v3

      - name: Clone backend repo
        uses: actions/checkout@v3
        with:
          repository: danielrdg/backend-dev-academy
          path: roteamento-ia-backend

      - name: Clone frontend repo
        uses: actions/checkout@v3
        with:
          repository: eduardo-r-rodrigues/frontend-dev-academy
          path: frontend-dev-academy

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Build and run services
        run: |
          docker-compose up --build -d